version: 2
jobs:
    build-prd:
        docker:
          - image: node:11.13
        steps:
          - add_ssh_keys:
              fingerprints:
                - "13:ae:99:56:4c:4c:a1:31:32:42:fd:42:83:70:88:88"
          - checkout
          - restore_cache:
                name: Restore pip dependency cache
                key: pip-v3-{{ checksum "requirements.txt" }}

          - run:
                name: Install rsync
                command: |
                    apt-get update
                    apt-get -y install openssh-client rsync
                    rsync -crtv --delete --exclude-from=exclude-list.txt -e 'ssh -i ~/.ssh/config' ./pages/ ubuntu@3.113.0.203:dir/
          - run:
                name: check
                command: rsync --version                


workflows:
    version: 2
    working:
        jobs:
          - build-prd:
                filters:
                    branches:
                        only: stg


