version: 2
jobs:
    build-prd:
        docker:
          - image: node:11.13
        steps:
          - checkout
          - restore_cache:
                name: Restore pip dependency cache
                key: pip-v3-{{ checksum "requirements.txt" }}

          - run:
                name: check
                command: yum -y install rsync
          - run:
                name: check
                command: rsync --version                


workflows:
    version: 2
    working:
        jobs:
          - build-prd:
                filters:
                    branches:
                        only: stg


