version: 2
jobs:
    build-prd:
        docker:
          - image: node:11.13
        steps:
          - add_ssh_keys:
              fingerprints:
                - "52:15:d1:c7:06:a9:4a:ba:9b:b1:ad:5f:bc:bb:25:b4"
          - checkout
          - restore_cache:
                name: Restore pip dependency cache
                key: pip-v3-{{ checksum "requirements.txt" }}

          - run:
                name: Install rsync
                command: |
                    apt-get update
                    apt-get -y install openssh-client rsync
                    rsync -crtv --delete --exclude-from=exclude-list.txt -e 'ssh -oStrictHostKeyChecking=no -i ~/.ssh/config ' ./pages/ ubuntu@3.113.0.203:dir/
          - run:
                name: check
                command: rsync --version                


workflows:
    version: 2
    working:
        jobs:
          - build-prd:
                filters:
                    branches:
                        only: stg


